---
title: 'DATA 605: Computational Mathematics Discussion Board 14'
author: "Gabriel Campos"
date: "Last edited `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
  geometry: left=0.5cm,right=0.5cm,top=1cm,bottom=2cm
  pdf_document:
    latex_engine: xelatex
  html_notebook: default
urlcolor: blue
---

# Week 14 Discussion:

Pick any exercise in 8.8 of the calculus textbook.  Solve and post your solution.  If you have issues doing so, discuss them. 

In this course, do not attach files to any of the discussion posts.  Provide your code and commentary plus figures directly in the text box.  Many students don't download files or open other links.

Page 496 Exercise 8.8 Question 3 

Key Idea 8.8.1 gives the $n^{th}$ term of the Taylor series of common functions. In Exercises 3 – 6, verify the formula given in the Key Idea by finding the first few terms of the Taylor series of the given function and identifying a pattern.

3. $f(x)=e^x$; $c=0$

Page 487 explains

The Taylor series for $f(x)$ about $c$ is:

$f(x)= \sum_{n=0}^{\infty}\frac{f^{(n)}(c)}{n!}(x-c)^n$

The Taylor Series Expansion of a function f(x) is given by:

$f(x) =f(c)+f'(c)(x-c)+\frac{f''(c)}{2!}(x-c)^2+\frac{f^{(3)}(c)}{3!}(x-c)^3+...$

The given $c=0$ the Taylor expansion becomes:

$f(x)=f(0)+f'(0)x+\frac{f''(0)}{2!}x^2++\frac{f^{(3)}(0)}{3!}x^3+....$

The derivative $\frac{d}{dx}(e^x)=e^x$ 

Which makes making $f(0)=e^0=1,f'(0)=e^0=1,f''(0)=e^0=1....$ 

Meaning $f^{(n)}(x)=e^x$ for all $n$
**and at** $c=0$**;**

$f^{(n)}(0)=e^0=1$ for all $n$

Substituting we can write this out as $f(x)=1+x+\frac{x^2}{2!}+\frac{x^3}{3!}+...$ 

Or using the Taylor formula can generalize this as $T_n(x)=\frac{f^{(n)}(0)}{n!}x^n=\frac{1}{n!}x^n$

Which is also in fact our pattern of $\frac{x^n}{n!}$ and can be rewritten as $e^x=\sum_{n=0}^{\infty}\frac{x^n}{n!}$
