---
title: 'DATA 605: Computational Mathematics Discussion Board 15'
author: "Gabriel Campos"
date: "Last edited `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
  geometry: left=0.5cm,right=0.5cm,top=1cm,bottom=2cm
  pdf_document:
    latex_engine: xelatex
  html_notebook: default
urlcolor: blue
---

# Week 15 Discussion:

Pick any exercise in Chapter 12 of the calculus textbook.  Post the solution or your attempt.  Discuss any issues you might have had.

What were the most valuable elements you took away from this course?  

**In this course, do not attach files to any of the discussion posts.  Provide your code and commentary plus figures directly in the text box.  Many students don't download files or open other links.**

Page 698

Exercise 12.2

Question

**In Exercises 7 – 10, a set S is given.**

(a) **Give one boundary point and one interior point, when possible, of S.**
(b) **State whether S is open, closed, or neither.**
(c) **State whether S is bounded or unbounded.**


$S = \left\{ (x,y) \mid \frac{(x-1)^2}{4} + \frac{(y-3)^2}{9} \leq 1 \right\}$

page 689 from our calculus book states

**Definition 12.2.1** 

**Open Disk, Boundary and Interior Points, Open and Closed Sets, Bounded Sets**

i. An **open disk** $B$ in $\mathbb{R}^2$ centered at $(x_0, y_0$) with radius r is the set of all points $(x, y)$ such that $\sqrt{(x − x_0)^2 + (y − y_0)^2} < r$.

ii. Let $S$ be a set of points in $\mathbb{R}^2$. A point P in $\mathbb{R}^2$ is a **boundary point** of $S$ if all open disks centered at $P$ contain both points in $S$ and points not in $S$.

iii. A point $P$ in $S$ is an **interior point** of $S$ if there is an open disk centered at $P$ that contains only points in $S$.

iv. A set $S$ is **open** if every point in $S$ is an interior point.

v. A set $S$ is **closed** if it contains all of its boundary points.

vi. A set $S$ is **bounded** if there is an $M > 0$ such that the open disk, centered at the origin with radius $M$, contains $S$. A set that is not bounded is **unbounded**.


**NOTE:**

We know the general form of the ellipse equation is $\frac{(x-k)^2}{a^2}+\frac{(y-k)^2}{b^2}=1$ and from this we know

- This is an equation of an ellipse
- the center of the ellipse is $(h,k)$ meaning $h=1, \ k=3$ or $(1,3)$
- the length of the semi-minor axis of the ellipse is $a$
- the length of the semi-major axis of the ellipse is $b$

**Solution**

**Boundary**

for *(a) Give one boundary point...* I can use $x=1$ and substitute into the equation for our equality:

$\frac{(x-1)^2}{4} + \frac{(y-3)^2}{9}=1 \rightarrow \frac{(1-1)^2}{4} + \frac{(y-3)^2}{9}=1 \rightarrow y-3=\sqrt{9}$

which becomes $y = \pm 3 - 3$ which gives us $y=6$ and $y=0$

So our boundaries are $(1,6)$ or $(1,0)$.

**Interior point**

for *(a)... one interior point* I'll use a point within the boundaries $(1,4)$

which when substituted into our strict inequality $\frac{(x-1)^2}{4} + \frac{(y-3)^2}{9}<1$

$\frac{(1-1)^2}{4} + \frac{(4-3)^2}{9}<1 \rightarrow \frac{1}{9}<1$ holds true.

**Open/Closed**

Our solution for the equality which proved set $S$ contains all of its boundary points and definition point $v.$ shows that our set $S$ is **closed**.

**Bounded/Unbounded**

The semi-major axis along the y-direction is given as b or $\sqrt{9}$ from our original equation.

Our Horizontal extent is when $y=3$ (semi-major) and when substituted into our equality equation $\frac{(x-1)^2}{4} + \frac{(3-3)^2}{9}=1$ 
gives us $x= \pm 2 +1$ or $x=3$ or $x=-1$ showing our horizontal extent is $3-(-1)=span \ of \ 4$

This shows us that this equation is clearly bounded

Substituting the maximum $x$ value of $x=3$ into:

$\frac{(x-1)^2}{4} + \frac{(y-3)^2}{9}=1 \rightarrow \frac{(3-1)^2}{4} + \frac{(y-3)^2}{9}=1 \rightarrow 1 + \frac{(y-3)^2}{9}=1 \rightarrow y-3=0 \rightarrow y=3$

giving us the point $(3,3)$

likewise using the maximum $y=6$:

$\frac{(x-1)^2}{4} + \frac{(6-3)^2}{9}=1 \rightarrow \frac{(x-1)^2}{4} + 1=1 \rightarrow x=1$

giving us the point $(1,6)$

if we calculate the distance between these points from the origin we get

$d = \sqrt{(1-0)^2+(6-0)^2}=\sqrt{37}$ and $d = \sqrt{(3-0)^2+(3-0)^2}=\sqrt{18}$ making our closest value to $M \approx \sqrt{37}$

Therefore

$S \subseteq \left\{ (x,y) \mid x^2 + y^2 < \sqrt{37} \right\}$

